
# Board settings.
#BOARD = atmega328
BOARD = pro5v328

#MON_SPEED = 9600

# Where to find header files and libraries.
LIB_DIRS = ../../ /usr/share/arduino-100/libraries/Wire/ /usr/share/arduino-100/libraries/Wire/utility/

#include ../../../Makefile.master
include ../../../Arduino.mk

